repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.13
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.14.0
    hooks:
    -   id: reorder-python-imports
        exclude: ^notebooks/.
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        exclude: ^notebooks/.
    - id: no-commit-to-branch # Prevent committing to specific branches.
      args: ['--branch', 'main', '--branch', 'dev']
    -   id: check-merge-conflict # Prevent committing files that contain merge conflict strings.
        args: [--assume-in-merge] # Allows running the hook when there is no ongoing merge operation
