# This workflow runs Ruff to check code quality on push and pull request events.
# It uses the astral-sh/ruff-action GitHub Action to run Ruff with the default configuration.
name: Ruff

on: [ push, pull_request ]

branches: [ "dev" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
